"""maps for compoentn"""
PART_LIBRARY_MAP: dict[str, tuple[str, str]] = {
    "resistor":                 ("Device", "R"),
    "capacitor":                ("Device", "C"),
    "inductor":                 ("Device", "L"),
    "led":                      ("Device", "LED"),
    "diode":                    ("Device", "D"),
    "npn":                      ("Device", "Q_NPN_BEC"),
    "pnp":                      ("Device", "Q_PNP_BEC"),
    "nmos":                     ("Device", "Q_NMOS_GDS"),
    "pmos":                     ("Device", "Q_PMOS_GDS"),
    #single supply
    "op_amp":                   ("Amplifier_Operational", "LMV321"),
    "op_amp_dual_supply":       ("Amplifier_Operational", "LM741"),
    "voltage_reg":              ("Regulator_Linear", "AMS1117-3.3"),
    "atmega328p":               ("MCU_Microchip_ATmega", "ATmega328P-A"),
    "esp32":                    ("RF_Module", "ESP32-WROOM-32"),
    "stm32f103":                ("MCU_ST_STM32F1", "STM32F103C8Tx"),
    "usb_c":                    ("Connector", "USB_C_Receptacle_USB2.0_16P"),
    "header_1x4":               ("Connector_Generic", "Conn_01x04"),
    "crystal":                  ("Device", "Crystal"),
    "linear_voltage_regulator": ("Regulator_Linear", "LM317_TO-220"),
    "fuse":                     ("Device", "Fuse"),
    "connector":                ("Connector_Generic", "Conn_01x02"),
    "potentiometer":            ("Device", "R_Potentiometer"),
    "switch":                   ("Switch", "SW_Push"),
    "transformer":              ("Device", "Transformer_1P_1S"),
    "battery":                  ("Device", "Battery"),
    "zener":                    ("Device", "D_Zener"),
    "schottky":                 ("Device", "D_Schottky"),
}
